/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive JWT */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user (max 10 users) */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear auth cookie */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts for current user */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get account by ID */
        get: operations["getAccount"];
        /** Update an account */
        put: operations["updateAccount"];
        post?: never;
        /** Soft delete an account */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions with filtering and pagination */
        get: operations["listTransactions"];
        put?: never;
        /** Create a transaction */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk import transactions from CSV */
        post: operations["importTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get transaction by ID */
        get: operations["getTransaction"];
        /** Update a transaction */
        put: operations["updateTransaction"];
        post?: never;
        /** Soft delete a transaction */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List distinct categories used by the current user */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transaction-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transaction groups for current user */
        get: operations["listTransactionGroups"];
        put?: never;
        /** Create a transaction group with member transactions */
        post: operations["createTransactionGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transaction-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get transaction group with members */
        get: operations["getTransactionGroup"];
        /** Update a transaction group */
        put: operations["updateTransactionGroup"];
        post?: never;
        /** Soft delete a transaction group and its member transactions */
        delete: operations["deleteTransactionGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assets with portfolio summary */
        get: operations["listAssets"];
        put?: never;
        /** Create an asset */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/allocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio allocation breakdown over time */
        get: operations["getAssetAllocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get asset with value history */
        get: operations["getAsset"];
        /** Update asset value and metadata */
        put: operations["updateAsset"];
        post?: never;
        /** Soft delete an asset */
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get value history time series */
        get: operations["getAssetHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List goals ordered by priority */
        get: operations["listGoals"];
        put?: never;
        /** Create a goal */
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update priority rankings */
        put: operations["reorderGoals"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get goal with computed projections */
        get: operations["getGoal"];
        /** Update a goal */
        put: operations["updateGoal"];
        post?: never;
        /** Soft delete a goal */
        delete: operations["deleteGoal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{id}/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** List contributions for a goal */
        get: operations["listGoalContributions"];
        put?: never;
        /** Record a contribution toward a goal */
        post: operations["createGoalContribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{id}/contributions/{contribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
                contribution_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a contribution and reverse its effect on the goal */
        delete: operations["deleteGoalContribution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recurring transactions */
        get: operations["listRecurring"];
        put?: never;
        /** Create a recurring transaction */
        post: operations["createRecurring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a recurring transaction */
        put: operations["updateRecurring"];
        post?: never;
        /** Deactivate a recurring transaction */
        delete: operations["deleteRecurring"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated dashboard data */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/net-worth-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth time series */
        get: operations["getNetWorthHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute financial projection */
        post: operations["computeProjection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List unread alerts */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        get?: never;
        /** Mark alert as read */
        put: operations["markAlertRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full JSON dump of all user data */
        get: operations["exportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CSV dump of transactions */
        get: operations["exportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Frontend Web Vitals ingestion */
        post: operations["postVitals"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: components["schemas"]["ErrorCode"];
                message: string;
                request_id: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        ErrorCode: "VALIDATION_FAILED" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL_ERROR";
        PaginationMeta: {
            page: number;
            per_page: number;
            total: number;
            total_pages: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
        };
        /** @enum {string} */
        TransactionType: "expense" | "deposit" | "transfer";
        /** @enum {string} */
        AccountType: "checking" | "savings" | "hysa" | "credit_card" | "mortgage" | "brokerage" | "retirement_401k" | "retirement_ira" | "retirement_roth_ira" | "rollover_ira" | "hsa" | "crypto_wallet" | "safe_agreement" | "credit_line" | "venmo" | "other";
        /** @enum {string} */
        AssetType: "liquid" | "retirement" | "real_estate" | "brokerage" | "speculative" | "other";
        /** @enum {string} */
        GoalType: "debt_payoff" | "savings";
        /** @enum {string} */
        Currency: "USD" | "BTC" | "ETH" | "EUR";
        /** @enum {string} */
        Frequency: "weekly" | "biweekly" | "monthly" | "quarterly" | "yearly";
        /** @enum {string} */
        AlertSeverity: "info" | "warning" | "critical";
        /** @enum {string} */
        Scenario: "best" | "average" | "worst";
        CreateAccountRequest: {
            name: string;
            institution: string;
            account_type: components["schemas"]["AccountType"];
            currency?: components["schemas"]["Currency"];
        };
        UpdateAccountRequest: {
            name?: string;
            institution?: string;
            account_type?: components["schemas"]["AccountType"];
            currency?: components["schemas"]["Currency"];
            is_active?: boolean;
        };
        AccountResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            institution: string;
            account_type: components["schemas"]["AccountType"];
            currency: components["schemas"]["Currency"];
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AccountListResponse: {
            data: components["schemas"]["AccountResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        CreateTransactionRequest: {
            type: components["schemas"]["TransactionType"];
            category: string;
            tags?: string[];
            amount: number;
            currency?: components["schemas"]["Currency"];
            /** Format: date */
            date: string;
            /** Format: uuid */
            account_id: string;
            notes?: string;
            is_recurring?: boolean;
            /** Format: uuid */
            group_id?: string;
        };
        UpdateTransactionRequest: {
            type?: components["schemas"]["TransactionType"];
            category?: string;
            tags?: string[];
            amount?: number;
            currency?: components["schemas"]["Currency"];
            /** Format: date */
            date?: string;
            /** Format: uuid */
            account_id?: string;
            notes?: string;
            is_recurring?: boolean;
            /** Format: uuid */
            group_id?: string;
        };
        TransactionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            account_id: string;
            type: components["schemas"]["TransactionType"];
            category: string;
            amount: number;
            currency: components["schemas"]["Currency"];
            /** Format: date */
            date: string;
            notes?: string;
            is_recurring: boolean;
            /** Format: uuid */
            recurring_transaction_id?: string;
            /** Format: uuid */
            group_id?: string;
            tags: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TransactionListResponse: {
            data: components["schemas"]["TransactionResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        ImportResponse: {
            imported: number;
            errors: {
                row: number;
                message: string;
            }[];
        };
        CreateTransactionGroupRequest: {
            name: string;
            members: components["schemas"]["TransactionGroupMemberInput"][];
        };
        TransactionGroupMemberInput: {
            type: components["schemas"]["TransactionType"];
            category: string;
            amount: number;
            /** Format: date */
            date: string;
            /** Format: uuid */
            account_id: string;
            notes?: string;
            tags?: string[];
        };
        UpdateTransactionGroupRequest: {
            name?: string;
            members?: components["schemas"]["TransactionGroupMemberUpdate"][];
        };
        TransactionGroupMemberUpdate: {
            /** Format: uuid */
            id?: string;
            type: components["schemas"]["TransactionType"];
            category: string;
            amount: number;
            /** Format: date */
            date: string;
            /** Format: uuid */
            account_id: string;
            notes?: string;
            tags?: string[];
        };
        TransactionGroupResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            total: number;
            members: components["schemas"]["TransactionResponse"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TransactionGroupListResponse: {
            data: components["schemas"]["TransactionGroupResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        CategoriesResponse: {
            categories: string[];
        };
        CreateAssetRequest: {
            name: string;
            asset_type: components["schemas"]["AssetType"];
            current_value: number;
            currency?: components["schemas"]["Currency"];
            /** Format: uuid */
            account_id?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        UpdateAssetRequest: {
            name?: string;
            asset_type?: components["schemas"]["AssetType"];
            current_value?: number;
            currency?: components["schemas"]["Currency"];
            /** Format: uuid */
            account_id?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        AssetResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            account_id?: string;
            name: string;
            asset_type: components["schemas"]["AssetType"];
            current_value: number;
            currency: components["schemas"]["Currency"];
            metadata?: {
                [key: string]: unknown;
            };
            linked_account?: components["schemas"]["LinkedAccountSummary"];
            history?: components["schemas"]["AssetHistoryEntry"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LinkedAccountSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            account_type: components["schemas"]["AccountType"];
            institution?: string;
            balance?: number;
        };
        AssetHistoryEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            asset_id: string;
            value: number;
            /** Format: date-time */
            recorded_at: string;
        };
        AssetListResponse: {
            data: components["schemas"]["AssetResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
            summary: components["schemas"]["PortfolioSummary"];
        };
        PortfolioSummary: {
            total_value: number;
            allocation: components["schemas"]["AllocationEntry"][];
        };
        AllocationEntry: {
            asset_type: components["schemas"]["AssetType"];
            value: number;
            percentage: number;
        };
        AssetHistoryResponse: {
            /** Format: uuid */
            asset_id: string;
            entries: components["schemas"]["AssetHistoryEntry"][];
        };
        AllocationResponse: {
            snapshots: {
                /** Format: date */
                date: string;
                allocations: components["schemas"]["AllocationEntry"][];
            }[];
        };
        CreateGoalRequest: {
            name: string;
            goal_type: components["schemas"]["GoalType"];
            target_amount: number;
            current_amount?: number;
            /** Format: date */
            deadline?: string;
            /** Format: uuid */
            linked_account_id?: string;
            priority_rank?: number;
        };
        UpdateGoalRequest: {
            name?: string;
            goal_type?: components["schemas"]["GoalType"];
            target_amount?: number;
            current_amount?: number;
            /** Format: date */
            deadline?: string;
            /** Format: uuid */
            linked_account_id?: string;
            priority_rank?: number;
        };
        GoalResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            goal_type: components["schemas"]["GoalType"];
            target_amount: number;
            current_amount: number;
            /** Format: date */
            deadline?: string;
            /** Format: uuid */
            linked_account_id?: string;
            priority_rank: number;
            required_monthly_contribution?: number;
            /** Format: date */
            projected_completion_date?: string;
            on_track?: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        GoalListResponse: {
            data: components["schemas"]["GoalResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        GoalReorderRequest: {
            rankings: {
                /** Format: uuid */
                id: string;
                priority_rank: number;
            }[];
        };
        CreateGoalContributionRequest: {
            amount: number;
            notes?: string;
            /** Format: date */
            contributed_at?: string;
            /** Format: uuid */
            transaction_id?: string;
        };
        GoalContributionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            goal_id: string;
            /** Format: uuid */
            user_id: string;
            amount: number;
            notes?: string;
            /** Format: uuid */
            transaction_id?: string;
            /** Format: date */
            contributed_at: string;
            /** Format: date-time */
            created_at: string;
        };
        GoalContributionListResponse: {
            data: components["schemas"]["GoalContributionResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        CreateRecurringRequest: {
            /** Format: uuid */
            account_id: string;
            type: components["schemas"]["TransactionType"];
            category: string;
            amount: number;
            currency?: components["schemas"]["Currency"];
            frequency: components["schemas"]["Frequency"];
            /** Format: date */
            next_occurrence: string;
        };
        UpdateRecurringRequest: {
            /** Format: uuid */
            account_id?: string;
            type?: components["schemas"]["TransactionType"];
            category?: string;
            amount?: number;
            currency?: components["schemas"]["Currency"];
            frequency?: components["schemas"]["Frequency"];
            /** Format: date */
            next_occurrence?: string;
            is_active?: boolean;
        };
        RecurringResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            account_id: string;
            type: components["schemas"]["TransactionType"];
            category: string;
            amount: number;
            currency: components["schemas"]["Currency"];
            frequency: components["schemas"]["Frequency"];
            /** Format: date */
            next_occurrence: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RecurringListResponse: {
            data: components["schemas"]["RecurringResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        DashboardResponse: {
            net_worth: number;
            net_worth_breakdown: {
                assets: number;
                cash: number;
                debt: number;
            };
            cash_flow_this_month: number;
            spending_by_category: {
                category: string;
                amount: number;
                percentage: number;
            }[];
            debts_summary: {
                /** Format: uuid */
                account_id: string;
                name: string;
                balance: number;
                monthly_payment: number;
                original_balance?: number;
                /** Format: date */
                payoff_date?: string;
                months_remaining?: number;
            }[];
        };
        NetWorthHistoryResponse: {
            data_points: {
                /** Format: date */
                date: string;
                value: number;
            }[];
        };
        ProjectionRequest: {
            /** @description Percentage adjustment to current savings rate */
            monthly_savings_adjustment?: number;
            return_rate?: number;
            years_to_project: number;
            one_time_events?: {
                amount: number;
                /** Format: date */
                date: string;
                /** @enum {string} */
                type: "windfall" | "expense";
            }[];
        };
        ProjectionResponse: {
            scenarios: {
                scenario: components["schemas"]["Scenario"];
                data_points: {
                    /** Format: date */
                    date: string;
                    value: number;
                }[];
                /** Format: date */
                millionaire_date?: string;
            }[];
        };
        AlertResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            alert_type: string;
            message: string;
            severity: components["schemas"]["AlertSeverity"];
            is_read: boolean;
            related_entity_type?: string;
            /** Format: uuid */
            related_entity_id?: string;
            /** Format: date-time */
            created_at: string;
        };
        AlertListResponse: {
            data: components["schemas"]["AlertResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        ExportResponse: {
            user: components["schemas"]["UserResponse"];
            accounts: components["schemas"]["AccountResponse"][];
            transactions: components["schemas"]["TransactionResponse"][];
            assets: components["schemas"]["AssetResponse"][];
            goals: components["schemas"]["GoalResponse"][];
            recurring_transactions: components["schemas"]["RecurringResponse"][];
            alerts: components["schemas"]["AlertResponse"][];
            /** Format: date-time */
            exported_at: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "unhealthy";
            version: string;
            uptime_seconds: number;
            /** @enum {string} */
            database: "connected" | "disconnected";
            /** Format: date-time */
            timestamp: string;
        };
        VitalsRequest: {
            metrics: {
                name: string;
                value: number;
                id?: string;
            }[];
        };
    };
    responses: {
        /** @description Validation failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdParam: string;
        PageParam: number;
        PerPageParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            /** @description Email already taken or user limit reached */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description Account updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
                account_id?: string;
                category?: string;
                type?: components["schemas"]["TransactionType"];
                date_from?: string;
                date_to?: string;
                amount_min?: number;
                amount_max?: number;
                /** @description Comma-separated tag names */
                tags?: string;
                search?: string;
                group_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    importTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** Format: uuid */
                    account_id: string;
                };
            };
        };
        responses: {
            /** @description Transactions imported */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTransactionGroups: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction group list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionGroupListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTransactionGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionGroupRequest"];
            };
        };
        responses: {
            /** @description Transaction group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionGroupResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTransactionGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction group detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionGroupResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTransactionGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionGroupRequest"];
            };
        };
        responses: {
            /** @description Transaction group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionGroupResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransactionGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction group deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset list with portfolio summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description Asset created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAssetAllocation: {
        parameters: {
            query?: {
                period?: "1m" | "3m" | "6m" | "1y" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allocation data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetRequest"];
            };
        };
        responses: {
            /** @description Asset updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAssetHistory: {
        parameters: {
            query?: {
                period?: "1m" | "3m" | "6m" | "1y" | "all";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetHistoryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listGoals: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalRequest"];
            };
        };
        responses: {
            /** @description Goal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    reorderGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalReorderRequest"];
            };
        };
        responses: {
            /** @description Goals reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalListResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalRequest"];
            };
        };
        responses: {
            /** @description Goal updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listGoalContributions: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contribution list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalContributionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createGoalContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalContributionRequest"];
            };
        };
        responses: {
            /** @description Contribution recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalContributionResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteGoalContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
                contribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contribution deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRecurring: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring transaction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringRequest"];
            };
        };
        responses: {
            /** @description Recurring transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringRequest"];
            };
        };
        responses: {
            /** @description Recurring transaction updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring transaction deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                spending_period?: "7d" | "30d" | "90d" | "1y";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getNetWorthHistory: {
        parameters: {
            query?: {
                period?: "1m" | "1y" | "5y" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Net worth history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthHistoryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    computeProjection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionRequest"];
            };
        };
        responses: {
            /** @description Projection result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    markAlertRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert marked as read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exportCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    postVitals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VitalsRequest"];
            };
        };
        responses: {
            /** @description Vitals recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
