global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pennywise"
    static_configs:
      - targets: ["localhost:8080"]
    metrics_path: "/metrics"
    scrape_interval: 15s

storage:
  tsdb:
    retention.time: 30d
